# Generated by Django 6.0.3 on 2026-03-15 23:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ansiedad', 'Ansiedad'), ('depresion', 'Depresión'), ('general', 'General')], default='general', max_length=20, verbose_name='Tipo de Encuesta')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('preguntas', models.JSONField(default=list, help_text='Array de preguntas en formato JSON', verbose_name='Preguntas')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado En')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado En')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'db_table': 'encuestas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('numero_empleado', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número de Empleado')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('password', models.CharField(max_length=350)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('id_departamento', models.IntegerField(blank=True, null=True, verbose_name='ID Departamento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado En')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado En')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(max_length=100, verbose_name='Email Destino')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('cuerpo', models.TextField(blank=True, default='', verbose_name='Cuerpo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('enviado_en', models.DateTimeField(blank=True, null=True, verbose_name='Enviado En')),
                ('mensaje_error', models.TextField(blank=True, default='', verbose_name='Mensaje de Error')),
                ('intentos', models.IntegerField(default=0, verbose_name='Intentos')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado En')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado En')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='api.encuesta', verbose_name='Encuesta')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RespuestasEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preguntas', models.JSONField(default=list, verbose_name='Preguntas')),
                ('respuestas', models.JSONField(default=list, verbose_name='Respuestas')),
                ('sesion_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID de Sesión')),
                ('contestadas_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Contestadas En')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado En')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado En')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='api.encuesta', verbose_name='Encuesta')),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta',
                'verbose_name_plural': 'Respuestas de Encuestas',
                'db_table': 'respuestas_encuesta',
                'ordering': ['-contestadas_en'],
                'indexes': [models.Index(fields=['empleado', 'encuesta'], name='respuestas__emplead_ad3b15_idx'), models.Index(fields=['sesion_id'], name='respuestas__sesion__560fc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEncuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('enviada', 'Enviada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('puntaje_total', models.IntegerField(blank=True, null=True, verbose_name='Puntaje Total')),
                ('interpretacion', models.CharField(blank=True, default='', max_length=50, verbose_name='Interpretación')),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20, verbose_name='Nivel de Riesgo')),
                ('recomendaciones', models.TextField(blank=True, default='', verbose_name='Recomendaciones')),
                ('iniciado_en', models.DateField(blank=True, null=True, verbose_name='Iniciado En')),
                ('fecha_completado', models.DateField(blank=True, null=True, verbose_name='Fecha Completado')),
                ('enviado_en', models.DateTimeField(auto_now_add=True, verbose_name='Enviado En')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado En')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado En')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api.encuesta', verbose_name='Encuesta')),
            ],
            options={
                'verbose_name': 'Resultado de Encuesta',
                'verbose_name_plural': 'Resultados de Encuestas',
                'db_table': 'resultado_encuestas',
                'ordering': ['-actualizado_en'],
                'unique_together': {('empleado', 'encuesta')},
            },
        ),
    ]
